---
- name: Run versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck | bool

- name: Resolv.conf is ino longer immutable.
  become: true
  ansible.builtin.file:
    path: '/etc/resolv.conf'
    attr: '-i'
  register: resolv_file
  changed_when: "resolv_file.changed and not resolveconf__immutable"
  ignore_errors: true

- name: Deploy resolv.conf
  block:
    - name: "Configure resolv.conf"
      become: true
      ansible.builtin.template:
        src: 'templates/resolv.conf.j2'
        dest: '/etc/resolv.conf'
        mode: "{{ resolvconf__mode }}"
        owner: root
        group: root
  rescue:
    - name: Remove /etc/resolv.conf
      become: true
      ansible.builtin.file:
        path: '/etc/resolv.conf'
        state: absent

    - name: "Try to deplpy resolv.conf again"
      become: true
      ansible.builtin.template:
        src: 'templates/resolv.conf.j2'
        dest: '/etc/resolv.conf'
        mode: "{{ resolvconf__mode }}"
        owner: root
        group: root

- name: Ensure resolv.conf is immutable.
  become: true
  ansible.builtin.file:
    path: '/etc/resolv.conf'
    attr: '+i'
  register: resolv_file
  changed_when: "not resolv_file.changed"
  when: resolveconf__immutable | bool
